name: Game Documentation
on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master
    
jobs:
  docs:
    runs-on: windows-latest
    steps:
      - name: Check Installed Software
        run: echo "Check Installed Software"
        
      - name: Checkout
        run: echo "Checkout"
        
      - name: Install Doxygen
        run: echo "Install Doxygen"
        
      - name: Run Doxygen
        run: echo "Run Doxygen"
        
      - name: Upload Docs
        run: echo "Upload Docs"
        
      - name: Setup Pages
        run: echo "Setup Pages"
        
      - name: Deploy to GitHub pages
        run: echo "Deploy to GitHub pages"
